insert into club(nom,poblacio,json)values('Llaurí, Club Pilota Valenciana (1990)','Llaurí','{"president":"Luis Fermin Cebolla Romeu","secretari":"Enrique Grau Cebolla"}');
insert into club(nom,poblacio,json)values('Vall Gallinera, Club Pilota Vicent Alminyana (1992)','Vall Gallinera','{"president":".","secretari":"."}');
insert into club(nom,poblacio,json)values('Murla, Club Pilota El Nel de Murla (1992)','Murla','{"president":"Pepe Torres","secretari":"David Sirera"}');
insert into club(nom,poblacio,json)values('Sant Joan d´Alacant, Beni Club San Joan (1987)','Sant Joan d´Alacant','{"president":"___","secretari":"__"}');
insert into club(nom,poblacio,json)values('Massalfasar, Club Pelotaris Massalfassar (1989)','Massalfasar','{"president":"Gabriel Soler Castello","secretari":"Joaquin Garibo Rafael"}');
insert into club(nom,poblacio,json)values('Meliana, Club Pilota Valenciana Meliana (1989)','Meliana','{"president":"Vicente Venancio Rel","secretari":"Ricardo Monsoriu Planells"}');
insert into club(nom,poblacio,json)values('Albal, Club Pilota (1989)','Albal','{"president":"Antonio Espinola","secretari":"___"}');
insert into club(nom,poblacio,json)values('Silla, Club Pilota Valenciana de Silla (1989)','Silla','{"president":"Pedro Escudero Brusel ","secretari":"Antonio Simarro Gascón "}');
insert into club(nom,poblacio,json)values('Benifaió, Club Pilota Valenciana Benifaió (1989)','Benifaió','{"president":"Vicente Pla San León/ Francisco Beltrán Segarra ","secretari":"José Tomás Iborra"}');
insert into club(nom,poblacio,json)values('Rafelguaraf, (1989) Club Pilota Rafelguaraf ','Rafelguaraf','{"president":"José Enrique San Miguel Juan","secretari":"Vicente Fayos Balaguer"}');
insert into club(nom,poblacio,json)values('Canals, Club Pilota A Ma Canals (1989)','Canals','{"president":"Francisco Aranda Gras","secretari":"Josep García Carbó"}');
insert into club(nom,poblacio,json)values('Carcaixent, Club Pilota Valenciana i de Raspall de Carcaixent (1993)','Carcaixent','{"president":"Enrique Estornell Llopis","secretari":"Enrique Estornell Molina"}');
insert into club(nom,poblacio,json)values('Godelleta, Club Pelotari Godelleta (1989)','Godelleta','{"president":"José Miguel Valero Aparicio","secretari":"Jaime Caballero Martínez"}');
insert into club(nom,poblacio,json)values('Benidorm, Club de Pilota Benidorm (1989)','Benidorm','{"president":"Antonio Calvo Orozco","secretari":"Francisco Juan Martínez"}');
insert into club(nom,poblacio,json)values('Benissa, Club Pilota Futur Benissa (1991)','Benissa','{"president":"Juan José Marín Ivars","secretari":"Juan Vicente Estela Crespo"}');
insert into club(nom,poblacio,json)values('Alquería de la Comtessa, Club Esportiu Conde (1991)','Alquería de la Comtessa','{"president":"José González Huesca","secretari":"Manuel Tur Verdú"}');
insert into club(nom,poblacio,json)values('Paiporta, Club Pilota Paiporta (1989)','Paiporta','{"president":"Alfredo Romero Romero","secretari":"Maxim Ruiz Ocheda"}');
insert into club(nom,poblacio,json)values('Castelló de la Plana, Club Pilotari Castelló (1987)','Castelló de la Plana','{"president":"Noemí Torrijos Benet","secretari":"Lluís Ramos i Santamaria"}');
insert into club(nom,poblacio,json)values('Llanera de Ranes, Club Pilota Llanera (1989)','Llanera de Ranes','{"president":"Agustín Tolosa Tolosa","secretari":"Jose Juan Palop Cuenca"}');
insert into club(nom,poblacio,json)values('Alfara del Patriarca,  Club de Pilota Valenciana (1989)','Alfara del Patriarca','{"president":"Honorato Navarro Porter","secretari":"Pau Giménez Guanter"}');
insert into club(nom,poblacio,json)values('Beniparrell, Club de Pilota Valenciana de Beniparrell (1989)','Beniparrell','{"president":"Antonio Martínez Ibáñez","secretari":"Carlos Costa Delhom "}');
insert into club(nom,poblacio,json)values('Alginet, Club Pilota Valenciana (1989) ','Alginet','{"president":"David Quiles i Asins","secretari":"Enric Quiles i Asins"}');
insert into club(nom,poblacio,json)values('Vilavieja, Club Pilotari La Vilavella (1989)','Vilavieja','{"president":"Samuel Adsuara Badenes/ José Pla Sanchis","secretari":"Juan Plà Roglà"}');
insert into club(nom,poblacio,json)values('Almenara, Club Pilotari Almenara (1989)','Almenara','{"president":"Joaquín Ferrer Caballer","secretari":"José Joaquín Arcos Fenollosa"}');
insert into club(nom,poblacio,json)values('Puçol, Club Peña Pelotaris de Puçol (1991)','Puçol','{"president":"Victor Gimeno Corbaton","secretari":"Alejandro Sancho Gallego "}');
insert into club(nom,poblacio,json)values('Montserrat, Club Pilota Valenciana Montserrat (1991)','Montserrat','{"president":"Federico Oliva Sala","secretari":"Pablo Cervero Sese"}');
insert into club(nom,poblacio,json)values('Riba-Roja de Túria, Club de Galotxa Riba-Roja de Túria (1989)','Riba-Roja de Túria','{"president":"Francisco Soriano Raga","secretari":"Antonio Arnau Betoret"}');
insert into club(nom,poblacio,json)values('Monóvar, Club Centro Deportivo Monóvar (1990)','Monóvar','{"president":"____","secretari":"___"}');
insert into club(nom,poblacio,json)values('Oliva, Club de Pilota Valenciana Oliva (1990)','Oliva','{"president":"Salvador Garcia Riesgo","secretari":"Joan Mata Cots"}');
insert into club(nom,poblacio,json)values('Sueca, Club Esportiu de Pilota Badana, (1992)','Sueca','{"president":"Manuel Conca Badía","secretari":"Joan Lluís Rodrigo Ventura"}');
insert into club(nom,poblacio,json)values('Vinalesa, Club Pilota Vilanesa (1992)','Vinalesa','{"president":"Julio Martínez Gallent","secretari":"Israel Sánchez Orts"}');
insert into club(nom,poblacio,json)values('Sollana, Club Pilota Valenciana Baixuquer (1990)','Sollana','{"president":"Germán Benito Albeldo/ Vicente Muñoz Barrajón","secretari":"Arturo Manuel Garulo Cambra"}');
insert into club(nom,poblacio,json)values('Valencia, Club Deportivo Universiad Politécnica Valencia (1986)','Valencia','{"president":"Ángel Benito Beorlegui","secretari":"Amparo Vidal Cuenca"}');
insert into club(nom,poblacio,json)values('Benicull, Club Pilota Valenciana Benicull (2013)','Benicull','{"president":"Salvador Boquera Candel","secretari":"Rafael Fayos Morant"}');
insert into club(nom,poblacio,json)values('Poblets (Els), Club Pilota VAlenciana Els Poblets (1992)','Poblets (Els)','{"president":"Lluís Moncho Ballester","secretari":"Francisco Bahamonde Ramis"}');
insert into club(nom,poblacio,json)values('Utiel, Club Natación Utiel (1990)','Utiel','{"president":"Alberto Moya Ballesteros","secretari":"Rafael Ariza Garcia"}');
insert into club(nom,poblacio,json)values('Teulada, Club de Pilota Teulada (1992)','Teulada','{"president":"Antonio Pedrós Pons","secretari":"Vicente Malonda Cervera"}');
insert into club(nom,poblacio,json)values('Sella, Club Pilota Sella (1986)','Sella','{"president":"David Màs Català","secretari":"Miguel Àngel Pérez Serrano"}');
insert into club(nom,poblacio,json)values('Albalat de la Ribera, Club Deportivo Cent Peus (1986)','Albalat de la Ribera','{"president":"Vicente Latorre Valero","secretari":"Raúl Saéz García"}');
insert into club(nom,poblacio,json)values('Bèlgida, Club de Pilotaris Font Freda de Bégida (1992)','Bèlgida','{"president":"Ángel Mas Micó","secretari":"Vicente Llorens Mollà"}');
insert into club(nom,poblacio,json)values('Catadau, Club Galotxa de Catadau (1992)','Catadau','{"president":"José Ismael Añó Climent","secretari":"Moises Climent Solaz"}');
insert into club(nom,poblacio,json)values('Almussafes, Club de Pilota Valenciana d´Almussafes (1992)','Almussafes','{"president":"José Ventura Salvador","secretari":"Josep Enric Folch Moreno"}');
insert into club(nom,poblacio,json)values('Poble Nou de Benitatxell, Club Pilota Poble Nou (1992)','Poble Nou de Benitatxell','{"president":"Francisco Malonda Cervera","secretari":"Guillermo Cardona Más"}');
insert into club(nom,poblacio,json)values('Pobla de Vallbona, Club El Racó de la Pilota (1989)','Pobla de Vallbona','{"president":"Pilar Castillo Faus","secretari":"Pascual Balaguer Castillo"}');
insert into club(nom,poblacio,json)values('Vall de Laguar (La), Club Pilota Valenciana La Vall de Laguart (1986)','Vall de Laguar (La)','{"president":"José Manuel Barber Mengual","secretari":"___"}');
insert into club(nom,poblacio,json)values('Petrer, Club de Pilota Valenciana Petrer (1990)','Petrer','{"president":"Francisco Amores Villena","secretari":"José Luis Hernández Monllor"}');
insert into club(nom,poblacio,json)values('Dénia, Club de Pilota Valenciana de Dènia (1992) ','Dénia','{"president":"Josep Enrique Vengut Lladosa","secretari":"Pepe Moll"}');
insert into club(nom,poblacio,json)values('Asp, Club A Dos de Pilota Valenciana  (1992)','Asp','{"president":"Emilio Mira Almodóvar","secretari":"Alfredo Miralles Pastor"}');
insert into club(nom,poblacio,json)values('Llombai, Club de Galotxa Llombai (1988)','Llombai','{"president":"Vicente Manclús Bonafé","secretari":"José Dorés Sanz"}');
insert into club(nom,poblacio,json)values('Borboto, Club de Pilota (1988)','Borboto','{"president":"Vicente Estellés Feliu","secretari":"José Marco Gibert"}');
insert into club(nom,poblacio,json)values('Benavites, Club Pilotari Benavites (1988)','Benavites','{"president":"Jorge López López","secretari":"Vicente Ramón Barberà Bueso"}');
insert into club(nom,poblacio,json)values('Navarrés Club de Pilota (2006)','','{"president":"Manolo Gomez Calderon ","secretari":"Vicente Ros Juan"}');
insert into club(nom,poblacio,json)values('Alaquàs, Club Pelota a Mano Villa de Alaquàs (1988)','Alaquàs','{"president":"Bonifacio Ruiz Toledo","secretari":"Bonifacio Ruiz Toledo"}');
insert into club(nom,poblacio,json)values('Alfafar, Club Grup de Pilota Centre Cultural Recreatiu (1988)','Alfafar','{"president":"José Giménez Azorín","secretari":"Conrado Ferrando Borruel"}');
insert into club(nom,poblacio,json)values('Ontinyent, Club de Pilota Valenciana d´Ontinyent (1988)','Ontinyent','{"president":"Manuel Navarro Sanchis","secretari":"José Manuel Soler Sanchis"}');
insert into club(nom,poblacio,json)values('Albuixech, Club de Pilota Valenciana (1988)','Albuixech','{"president":"Vicente Margaix Herraix","secretari":"Enrique Ruiz Sanjerónimo"}');
insert into club(nom,poblacio,json)values('Quart de les Valls Club de Pilota (1989)','','{"president":"Pasqual Romeu Forner ","secretari":"Artur Bayona Morale"}');
insert into club(nom,poblacio,json)values('Aldaia, Club de Pilota Valenciana (1988)','Aldaia','{"president":"Juan López Romero","secretari":"Vicente Puig Vilanova"}');
insert into club(nom,poblacio,json)values('Museros, Club de Galotxa Museros (1988)','Museros','{"president":"Vicente Simón Gimeno","secretari":"Jordi García Eulogio"}');
insert into club(nom,poblacio,json)values('Alfarp-Catadau-Llombai, Club de Pilota Valenciana (1988)','Alfarp-Catadau-Llombai','{"president":"Gerardo Añó Juanes","secretari":"Pedro Anaya Gil"}');
insert into club(nom,poblacio,json)values('Puig, Club Penya Pilotaris Amics del Frontó del Puig (1988)','Puig','{"president":"Vicente Pascual Tomás","secretari":"Pepe Oriola"}');
insert into club(nom,poblacio,json)values('Segart, Club Pelotaris Segart (1988)','Segart','{"president":"__","secretari":"___"}');
insert into club(nom,poblacio,json)values('Moncada, Club de Pilota Valenciana Moncada (1989)','Moncada','{"president":"Vicente Salvador Simó Bueno","secretari":"Vicent Marqués Gascó"}');
insert into club(nom,poblacio,json)values('Xirivella, Club de Pilota de Xirivella (1990)','Xirivella','{"president":"Roberto Monleón Sena/ Vicent Martí Sena","secretari":"Agustín Pastor Carrasco"}');
insert into club(nom,poblacio,json)values('Faura, Club Pilotaris (1989)','Faura','{"president":"Juan Bautista Camarelles Ros","secretari":"Álvaro Navarro Serra"}');
insert into club(nom,poblacio,json)values('Quart de les Valls Club de Pilota (1989)','','{"president":"Pasqual Romeu Forner ","secretari":"Artur Bayona Morale"}');
insert into club(nom,poblacio,json)values('Sollana Club de Galotxa (1989)','','{"president":"Josep Felip Blasco","secretari":"David Belda Sánchez"}');
insert into club(nom,poblacio,json)values('Massamagrell Club de Pilota (1989)','','{"president":"Antonio Furió Martínez","secretari":"Benjamin Eres Piquer"}');
insert into club(nom,poblacio,json)values('Polinyà del Xúquer Club de Raspall (1990)','','{"president":"Pablo Esteve Boix","secretari":"Vicente Chulià Escrivà"}');
insert into club(nom,poblacio,json)values('Castalla Club de Pilota Valenciana Nou Trinquet (1999)','','{"president":"Salvador Dura Milan","secretari":"José Paya Beneyto"}');
insert into club(nom,poblacio,json)values('València Club de Pilota Valenciana Pelaio Matemàtico Marzal (2002)','','{"president":"Arturo Tuzon Gómez","secretari":"Jose Manuel Albalat Guara"}');
insert into club(nom,poblacio,json)values('València Club Esportiu Santa Maria Micaela (1999)','','{"president":"José Ynat Marques","secretari":"Ana Isabel Garcés Puchol"}');
insert into club(nom,poblacio,json)values('Burjassot Club de Pilota Mendizabal (2002)','','{"president":"Javier Zanon Aguado","secretari":"Vicente Francisco Folch Cameran"}');
insert into club(nom,poblacio,json)values('Paterna Club de Pilota Valenciana  (2002)','','{"president":"Enrique Martí Ribas","secretari":"Antonio Damián Ferrandis "}');
insert into club(nom,poblacio,json)values('Cocentaina Club de Pilota (1998)','','{"president":"Ferran Borrell Gonsàlbez","secretari":"Rafael Enguix Ribelles"}');
insert into club(nom,poblacio,json)values('Otos Club de Pilota (1998)','','{"president":"David Fuster Boluda","secretari":"Federico Fuster Boluda"}');
insert into club(nom,poblacio,json)values('Almassora Club Pilotari (2000)','','{"president":"Santiago Solsona Pitarch","secretari":"Rafael Mulet Forner"}');
insert into club(nom,poblacio,json)values('Godella Club de Pilota Valenciana (1993)','','{"president":"Vicent Caballer Torres","secretari":"Joan Alonso Usero"}');
insert into club(nom,poblacio,json)values('Alcoi Club de Pilota Valenciana La Muntanya (1993)','','{"president":"Enrique Sevilla Maestre","secretari":"Armando Verdú Mira"}');
insert into club(nom,poblacio,json)values('Alcoi Club de Pilota Valenciana (1995)','','{"president":"Fernando Pastor Pastor","secretari":"Juli Sanchis Aguado"}');
insert into club(nom,poblacio,json)values('Gàtova Club de Pilota Valenciana (1998)','','{"president":"Ambrosio Esteve Piquer","secretari":"Miguel Ángel Sanchez Romero "}');
insert into club(nom,poblacio,json)values('Loriguilla Club de Pilota (1998)','','{"president":"Juan Isaac Oltra Moragues","secretari":"Jose Cervera Nicasio"}');
insert into club(nom,poblacio,json)values('Vila Joiosa CLub de Pilota Valenciana la Vila (2000)','','{"president":"Antonio Buades López","secretari":"Pedro Alexis Esquerdo Amorós"}');
insert into club(nom,poblacio,json)values('València Club de Pilota Valenciana Bot i Braç (2000)','','{"president":"Bernat Santabasilia Hernàndez","secretari":"Antoni Perez Canet"}');
insert into club(nom,poblacio,json)values('Beniarrés Club de Pilota (2000)','','{"president":"Juan Luis Tomas Sanchis","secretari":"Joan Josep Gilabert Valor"}');
insert into club(nom,poblacio,json)values('Castelló de la Plana CLub de Pilota Mezquita San Agustin i San Marcos (2000)','','{"president":"Alfredo Giménez Giménez","secretari":"Jose Borja Perez"}');
insert into club(nom,poblacio,json)values('El Campello Club de Pilota Valenciana (1996)','','{"president":"Josep Antoni Martínez Asensi","secretari":"Julià-Pere Garcia Soler"}');
insert into club(nom,poblacio,json)values('La Valldigna, Club de Pilota (1999)','La Valldigna','{"president":"Juan José Sala Escrihuela","secretari":"Salvador Bono Peiró"}');
insert into club(nom,poblacio,json)values('Genovés Club de Pilota (1999)','','{"president":"Juan Sanchis Cabanes","secretari":"Pasqual Oltra Sanjuan"}');
insert into club(nom,poblacio,json)values('València Club Associació Cultural i Esportiva Amics del  Maritim (1999)','','{"president":"Marinette Gascó Poy","secretari":"Juan Bautista Coll Cardona"}');
insert into club(nom,poblacio,json)values('Xilxes Club Amics de la Pilota Valenciana (1999)','','{"president":"Francisco Gomis Martinez ","secretari":"Joaquin Manzano Sanz"}');
insert into club(nom,poblacio,json)values('Bicorb Club de Pilotaris (2000)','','{"president":"Vicente Juan Molla Pérez","secretari":"Armando Mercé Vidal "}');
insert into club(nom,poblacio,json)values('Bellrreguard A.Esportiva (1989)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Carlet Club de Pilota Valenciana (1994)','','{"president":"José Iglesias Herbàs","secretari":"David Martínez Rey"}');
insert into club(nom,poblacio,json)values('Mutxamel Club de Pilota Valenciana (1994)','','{"president":"José Francisco Berenguer Pérez","secretari":"Borja Berenguer Evora"}');
insert into club(nom,poblacio,json)values('Xeraco Club de Pilota Raspall (2001)','','{"president":"Adelí Estornell Canet","secretari":"Jose Vicente Rubio Bofí"}');
insert into club(nom,poblacio,json)values('Traiguera Club de Pilota Valenciana (2001)','','{"president":"Amador Peset Celma","secretari":"Santiago Salvador Llatser"}');
insert into club(nom,poblacio,json)values('València Club de Pilota Valenciana Sagunt-San Guillem (2001)','','{"president":"Monica Ballester Campo","secretari":"Jose Vicente Chabert Linares"}');
insert into club(nom,poblacio,json)values('València Club de Pilota Valenciana Montortal-Torrefiel (2001)','','{"president":"Francisco Orti Bolumar","secretari":"Javier Ortiz Coret"}');
insert into club(nom,poblacio,json)values('Xàbia Club de Pilota (1994)','','{"president":"Josep Sapena Segarra","secretari":"Jaime Segarra López"}');
insert into club(nom,poblacio,json)values('Parcent, Club de Pilota Parcent (2001)','Parcent','{"president":"Vicente Frances Comes","secretari":"Juan Herminio Pérez Moncho"}');
insert into club(nom,poblacio,json)values('Bunyol, Club Amics Joc de Pilota Valenciana Galotxa','Bunyol','{"president":"Francisco Alcañiz Valles ","secretari":"Alicia Hernández Carrascosa"}');
insert into club(nom,poblacio,json)values('Sueca, Club Pilota Valenciana Xúquer de Sueca (2015)','Sueca','{"president":"Bernat Nerbón Vendrell","secretari":"Raul Amatud San Lorenzo"}');
insert into club(nom,poblacio,json)values('Tibi, Club de Pilota Tibi (2001)','Tibi','{"president":"Isaac García Bernabeu","secretari":"Eladio Mira Cremades"}');
insert into club(nom,poblacio,json)values('Ondara Club de Pilota Valenciana (1994)','','{"president":"Francisco Manuel Martínez Noguera","secretari":"Francesc Josep Frasés i Soler"}');
insert into club(nom,poblacio,json)values('Campanar Club de Pilota Valenciana (1988)','','{"president":"-","secretari":"Enrique Salom Garcia"}');
insert into club(nom,poblacio,json)values('Foios Club de Pilota Valenciana (1989)','','{"president":"Fernando Gil Agulló ","secretari":"Angel Tamarit Rausell"}');
insert into club(nom,poblacio,json)values('Lliria, Club de Pilota Valenciana Lliria (1997)','Lliria','{"president":"Esperanza Pérez Herraiz","secretari":"Trinitario Rodilla Castillo"}');
insert into club(nom,poblacio,json)values('Monòver Club Galotxetes de Monòver (1990)','','{"president":"Marcos Antonio Paya Garcia","secretari":"Luis Galiano Giner"}');
insert into club(nom,poblacio,json)values('Borriol Club de Pilota Valenciana (2001)','','{"president":"Eliseo Tena Sanchez","secretari":"Ramón Linares Safont"}');
insert into club(nom,poblacio,json)values('Borriana, Club Pilotari Borriana la Teua Mar (1997)','Borriana','{"president":"Leonardo Daudi Safont","secretari":"Juan Francisco Viñez Dosda"}');
insert into club(nom,poblacio,json)values('Murla Club de Pilota Valenciana Jose Vte Riera Clatayud. El Nel (1997)','','{"president":"Juan Manuell Reig Valero","secretari":"Sebastià Giner Muñoz"}');
insert into club(nom,poblacio,json)values('Quart de Poblet Club de Pilota a Ma (1997)','','{"president":"Ignacio Ramos Godoy ","secretari":"Manuel Villar Zarzuela"}');
insert into club(nom,poblacio,json)values('Alzira Club de Pilota Valenciana (1995)','','{"president":"Eduardo Lopez-Pintor Benavent","secretari":"Eduardo Lopez-Pintor Madrid"}');
insert into club(nom,poblacio,json)values('Albalat de Sorells, Club de Pilota Valenciana Balatans (1997)','Albalat de Sorells','{"president":"Juan José Ortega Vico","secretari":"Miguel Santiago Almenar Campos"}');
insert into club(nom,poblacio,json)values('Bonrepós i Miranvell CLub Amics de la Pilota (1997)','','{"president":"Jose Luis Rodrigo Forés ","secretari":"Miguel Esteve Forés"}');
insert into club(nom,poblacio,json)values('Moncofa Club de Pilota Moncofense (1999)','','{"president":"Carlos Dominguez Rodriguez","secretari":"José Arnau Alemany "}');
insert into club(nom,poblacio,json)values('Meliana Club de Pilota Valenciana La Pedrera (2002)','','{"president":"Francisco Casares Ubach","secretari":"Artur Cortina Garcia"}');
insert into club(nom,poblacio,json)values('Bolbaite Club de Pilota (2002)','','{"president":"Enrique Navalon Estarlich","secretari":"Amparo Merlos Peña"}');
insert into club(nom,poblacio,json)values('Montroy Club Societat de Pilota Galotxa (1995)','','{"president":"José Cebria Ribes ","secretari":"Florecio Javier Clemente Gil"}');
insert into club(nom,poblacio,json)values('Les Useres, Futbol Sala Secció Pilota Valenciana (2004)','Les Useres','{"president":"Francisco Llinares Doningo","secretari":"--"}');
insert into club(nom,poblacio,json)values('València Club de Pilota Universitari El Tamborí (1997)','','{"president":"JOan Antoni Gregori Márquez","secretari":"Josep Tarín Bosque"}');
insert into club(nom,poblacio,json)values('Gandia Club de Pilota Valenciana (1999)','','{"president":"Emilio Peris Mascarell","secretari":"Juan Miguel Vañó Victoria"}');
insert into club(nom,poblacio,json)values('Vila-real Club Pilotari (1999)','','{"president":"Manuel Font Serra","secretari":"Francisco Zurita Mata"}');
insert into club(nom,poblacio,json)values('Algemesí, Club Esportiu Colla de Pilotaires (1999)','Algemesí','{"president":"Plàcid Navarro i Castanyer ","secretari":"Jordi Maravilla Herraiz"}');
insert into club(nom,poblacio,json)values('Moixent Club Esport base (2007)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Almoines Club de Pilota Valenciana (2005)','','{"president":"Jesus Mengual Garcia","secretari":"Jesus Morant Olcina"}');
insert into club(nom,poblacio,json)values('Castelló de Rugat Club de Pilota Valenciana (2005)','','{"president":"Aruturo Palau Fuster","secretari":"Elena Barrana Barranca"}');
insert into club(nom,poblacio,json)values('Pobla del Duc Club de Pilota Valenciana Trencamans (2005)','','{"president":"Juan Bataller Soler","secretari":"Jose Soler Garcia"}');
insert into club(nom,poblacio,json)values('Callosa d´En Sarrià Club de Pilota Valenciana Algar (2005)','','{"president":"Juan José Calvo Valls","secretari":"Francisco Cortell Chesa"}');
insert into club(nom,poblacio,json)values('Albaida, Club de Pilota Valenciana Ciutat d´Albaida (2005)','Albaida','{"president":"Manuel Ramos Soler","secretari":"Iván Segarra Lluch"}');
insert into club(nom,poblacio,json)values('Benicolet Club de Pilota Valenciana (2002)','','{"president":"Vicent Joan Martínez Soler","secretari":"Fernando Centelles Arias"}');
insert into club(nom,poblacio,json)values('Lloc Nou d´En Fenollet, Club Pilota Valenciana Fenollet (2013)','Lloc Nou d´En Fenollet','{"president":"Jorge Perales Vidal","secretari":"Félix Cabanes Tormo"}');
insert into club(nom,poblacio,json)values('Real de Gandia Club de Pilota Valenciana (2005)','','{"president":"Vicente Eugenio Signes Mas","secretari":"Salvador Garcia Juan "}');
insert into club(nom,poblacio,json)values('El Palomar Club de Pilota (2005)','','{"president":"Jose Luis Dura Soler","secretari":"Jose Alfonso Vidal Garcia"}');
insert into club(nom,poblacio,json)values('Piles Club de Pilota Valenciana (2005)','','{"president":"José María Puig Girau","secretari":"Vicente Aparicio Ciscar"}');
insert into club(nom,poblacio,json)values('Foios CLub de Pilota Xiquet de Foios (2005)','','{"president":"Joaquin Gabila Celda","secretari":"Eulalia Ferrer Badia "}');
insert into club(nom,poblacio,json)values('València Club de Pilota Valenciana El Carxot (2007)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Casinos Club de Pilota Valenciana (2009)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Sot de Chera Club de Pilota Valenciana (2008)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Atzeneta del Maestrat Club de Pilota Valenciana D´Atzeneta (2003)','','{"president":"Carlos Roig Escrig","secretari":"Miguel Juan Fabra"}');
insert into club(nom,poblacio,json)values('Vilamarxant, Club de Pilota Valenciana Vilamarxant (2003)','Vilamarxant','{"president":"Antonio Monrabal Golpe","secretari":"Miquel Quiles Olmeda"}');
insert into club(nom,poblacio,json)values('Massamagrell Club de Pilota Valenciana El Rebot (2006)','','{"president":"Ramon Tamarit Ferrer","secretari":"Vicente Galan Ronda"}');
insert into club(nom,poblacio,json)values('Pobla de Vallbona Club de Galotxa (2009)','','{"president":"Vte. Isidro Sánchez Pérez","secretari":"F.Javier Castillo Capella"}');
insert into club(nom,poblacio,json)values('El Verger, Club de Pilota Valenciana El Verger (2006)','El Verger','{"president":"Francisco Tomas Ferrando","secretari":"--"}');
insert into club(nom,poblacio,json)values('Meliana, Club de Pilota Valenciana (1996)','Meliana','{"president":"José Orts Lleida","secretari":"Ricardo Monsoriu Planells"}');
insert into club(nom,poblacio,json)values('Monforte Del Cid Club de Pilota Valenciana (2008)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Gaibiel, Club Pelotari Alto Palancia Gaibiel (2010)','Gaibiel','{"president":"Ricardo Mesado Mateu","secretari":"Jose Luis Perez Campos"}');
insert into club(nom,poblacio,json)values('Alcoi Club Deportivo Cotes Baixes (2006)','','{"president":"Jesus Cuenca Rubio","secretari":"Lourdes Carbonell Pascual"}');
insert into club(nom,poblacio,json)values('Rafelbunyol Club de Pilota Valenciana (1993)','','{"president":"Josep Antoni Jover Castellar","secretari":"Josep Antoni Jover Castellar"}');
insert into club(nom,poblacio,json)values('Torreblanca Club de Pilota Valenciana (2008)','','{"president":"Ivan Sales Torres","secretari":"Jose Vicente Sospedra Sales"}');
insert into club(nom,poblacio,json)values('Alqueria d´Asnar Club de Pilota Valenciana (2003)','','{"president":"Daniel Vidal Montalva","secretari":"Daniel Vidal Gonzàlez"}');
insert into club(nom,poblacio,json)values('Llutxent Club de Pilota Valenciana (2003)','','{"president":"Leonardo Canet Canet","secretari":"Adrian Badenes Garcia"}');
insert into club(nom,poblacio,json)values('Alberic, Club de Pilota Valenciana Maxim-Domenech (2003)','Alberic','{"president":"Joaquín Gisbert Armengol","secretari":"Ramon Marcos Marín Colomer"}');
insert into club(nom,poblacio,json)values('Onda Club Pilotari d´Onda (2003)','','{"president":"Ricardo Baraldes Mir","secretari":"Pedro Luis Desanantonio Tomàs"}');
insert into club(nom,poblacio,json)values('Benidoleig Club de Pilota Valenciana (2003)','','{"president":" Juan Mengual Poquet","secretari":"Luis Miguel Ballester Borja"}');
insert into club(nom,poblacio,json)values('Sagunt Club de Pilota (1998)','','{"president":"Jesus Soriano Blesa","secretari":"Felipe Espinosa Rico"}');
insert into club(nom,poblacio,json)values('Moncofa Club de Pilota ´Antonio Nuñez´ (2004)','','{"president":"Wenceslao Arnau Ferrando","secretari":"Wenceslao Arnau Martí"}');
insert into club(nom,poblacio,json)values('Pedreguer Club de Pilota Valenciana (2004)','','{"president":"Juan Mateu Salva Alberola","secretari":"Pablo Sala Reig"}');
insert into club(nom,poblacio,json)values('Alacant, Club de Pilota Valenciana (2009)','Alacant','{"president":"Hector Bautista Sala ","secretari":"Josep Miquel Garcia Martin "}');
insert into club(nom,poblacio,json)values('Tavernes Blanques Club de Pilota Valenciana ´Paco Sorní´ (2010)','','{"president":"Luis Lluch Lluch","secretari":"--"}');
insert into club(nom,poblacio,json)values('Quart de les Valls Club de Pilota Valenciana (2010)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Villar del Arzobispo Club de Pilota (1988)','','{"president":"Vidal López Balaguer","secretari":"Benedicto Vijuescas Ros"}');
insert into club(nom,poblacio,json)values('Aielo de Rugat, Club de Pilota Valenciana (2010)','Aielo de Rugat','{"president":"Roberto Albert Durà","secretari":"--"}');
insert into club(nom,poblacio,json)values('Benicarló Club de Pilota Valenciana Arrea-li Bona (2009)','','{"president":"Jordi Lores Peña","secretari":"--"}');
insert into club(nom,poblacio,json)values('Gata de Gorgos Club de Pilota Valenciana (2009)','','{"president":"Jose Miguel Ferrer Lleyda","secretari":"Pep Mulet Pedros"}');
insert into club(nom,poblacio,json)values('Hondón de las Nieves  Club de Pilota Valenciana Las Nieves (2004)','','{"president":"Francisco Alpera Tenza","secretari":"Vicente Pastor Pastor"}');
insert into club(nom,poblacio,json)values('Rafelbunyol Club de Pilota Valenciana Carrer de dalt (2004)','','{"president":"Lluis Borras Carpena","secretari":"Julio Ramon Camarasa"}');
insert into club(nom,poblacio,json)values('Font d´en Carròs Club de Pilota Valenciana Monzó i Godofredo (2009)','','{"president":"Juan Fuster Ribes","secretari":"Jose Maria Escrivà Pons"}');
insert into club(nom,poblacio,json)values('Quartell  Club de Pilota Valenciana (2006)','','{"president":"Ferran Ferrer Ribera","secretari":"Peregrín Ribera Cuenca"}');
insert into club(nom,poblacio,json)values('La Nucia  Club de Pilota Valenciana (2004)','','{"president":"Fernando Flores Rigby","secretari":"Daniel Flores Rigby"}');
insert into club(nom,poblacio,json)values('Rafelbunyol Club de Pilota Valenciana L´Illa del Raspall (2006)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Alfàs del Pi  Club de Pilota (1995)','','{"president":"Jesús Alcoi Pons","secretari":"Rosendo Olmedo Albiñana"}');
insert into club(nom,poblacio,json)values('València Club de Pilota Valenciana Pelaio (2009)','','{"president":"Celestino Bendicho Mercader","secretari":"Javier Pastor Moreno"}');
insert into club(nom,poblacio,json)values('València Club de Pilota Falla Perez Galdos Jesus Maestro Sosa (2004) ','','{"president":"Victor Javier Benaches Tortosa ","secretari":"Santiago Jesus Avellaneda Canet "}');
insert into club(nom,poblacio,json)values('Atzeneta d´Albaida  Club de Pilota Valenciana (2004)','','{"president":"Jose German Nacher Calatayud","secretari":"Vicent Ramón Nácher Ferri"}');
insert into club(nom,poblacio,json)values('Sueca, Club de Pilota Valenciana Amics de la Pilota (2009)','Sueca','{"president":"Adrián Miguel Mascarell","secretari":"Rafael Santacreu Mascarell"}');
insert into club(nom,poblacio,json)values('Xixona  Club de Pilota Valenciana (2009)','','{"president":"Jonathan Gras Murillo","secretari":"Lucas Alcaraz Domínguez"}');
insert into club(nom,poblacio,json)values('Albalat de la Ribera, Club de Pilota Valenciana la Llotgeta d´Albalat de la Ribera (2014)','Albalat de la Ribera','{"president":"Raúl Sáez García","secretari":"Felipe Navarro Súñer"}');
insert into club(nom,poblacio,json)values('Benifallim  Club de Pilota Valenciana Perxa (2009)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Finestrat  Club de Pilota Valenciana (1998) ','','{"president":"Amtonio Llorca Miralles ","secretari":"José Vicente Pérez Mengual "}');
insert into club(nom,poblacio,json)values('Benasau  Club de Pilota Valenciana (2004)','','{"president":"Salvador Gadea Peña ","secretari":"Juan Bautista Oltra Grau "}');
insert into club(nom,poblacio,json)values('Relleu  Club de Pilota Valenciana (2005)','','{"president":"Pere Cantó Casanova","secretari":"Moisés Ruiz Garcia"}');
insert into club(nom,poblacio,json)values('Alcàntera del Xúquer-Càrcer,  Club de Pilota Valenciana `El Moro` (2010)','Alcàntera del Xúquer-Càrcer','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Torrent  Club de Pilota Valenciana Trinquet de Torrent (2009)','','{"president":"Juan Antonio Zamora Fernandez","secretari":"Juan Antonio Zamora Moreno "}');
insert into club(nom,poblacio,json)values('Càrcer  Club de Pilota Valenciana La Vall (2004)','','{"president":"Vicente Miguel Domenech Botella ","secretari":"Antonio Estadelles Pascual "}');
insert into club(nom,poblacio,json)values('Sant Vicent,  Club de Pilota Valenciana Sant Vicent del Raspeig (2013)','Sant Vicent','{"president":"José Miguel Santacreu Cortés","secretari":"Pascual Tomás Maciá"}');
insert into club(nom,poblacio,json)values('Xaló Club de Pilota Valenciana (2004)','','{"president":"Jose Martin Avellà Ferrà","secretari":"Vicente David Molines Vives "}');
insert into club(nom,poblacio,json)values('Quesa Club de Pilota Valenciana (2010)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Beniganim, Club de Pilota Valenciana (2010)','Beniganim','{"president":"Juan Ramón Boluda Cuquerella","secretari":"Miguel Ángel Boluda Cuquerella"}');
insert into club(nom,poblacio,json)values('Polop Club Grup Pilota a Carrer (1995)','','{"president":"Vicent Orts Iborra","secretari":"Carlos Gualde Rodríguez"}');
insert into club(nom,poblacio,json)values('Burriana, Club de Pilota Valenciana Burriana (2005)','Burriana','{"president":"Juan Bautista Rubert Nebot","secretari":"Cristian Castelló Rubert"}');
insert into club(nom,poblacio,json)values('Castelló de la Ribera Club de Pilota Valenciana Castellonense (2009)','','{"president":"Jua José Calatayud Vila ","secretari":"Ricard Sentandreu Ferrando "}');
insert into club(nom,poblacio,json)values('Manises Club de Pilota Valenciana (1998)','','{"president":"Antonio Serra Latorre","secretari":"Manuel Taberner Sancho"}');
insert into club(nom,poblacio,json)values('Crevillent Club de Pilota Valenciana (1987) ','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Pinoso Club Llonges EL Pinos (1990)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Alfara de la Baronía, Club de Pilota Valenciana (2010)','Alfara de la Baronía','{"president":"Raul Herrera Duran ","secretari":"Raquel Martínez Puertas"}');
insert into club(nom,poblacio,json)values('Alcàsser, Club de Pilota Valenciana (2009)','Alcàsser','{"president":"Daniel Martos Garcia","secretari":"Guillem Torrent Benavent "}');
insert into club(nom,poblacio,json)values('Alcublas Club de Pilota Valenciana (2009)','','{"president":"Carlos Anton Alcaide","secretari":"Guillermo Tortajada Comecme"}');
insert into club(nom,poblacio,json)values('Ador, Club de Pilota Valenciana La Murtera (2005)','Ador','{"president":"Juan Vicente Estruch Puig ","secretari":"Juan Belda Sendra"}');
insert into club(nom,poblacio,json)values('Simat de la Valldigna Club de Pilota Valenciana (2009)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Muro d´Alcoi Club de Pilota Valenciana Muro (2009) ','','{"president":"Juan Gázquez Masià","secretari":"Sergio Roca Perea"}');
insert into club(nom,poblacio,json)values('Chiva Club de Pilota Valenciana (2009)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Quatretonda Club de Raspall (2009)','','{"president":"Juan Vicente Canet Benavent","secretari":"Jaime Oltra Benavent"}');
insert into club(nom,poblacio,json)values('Manuel Amics de la Pilota (2000)','','{"president":"Jose Manuel Moncho Esparza ","secretari":"Francesc Bonet Marcos"}');
insert into club(nom,poblacio,json)values('València Sec.Dep.Pilota Valenciana de l´Associació Jovens Joans (2003)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Algimia d´Alfara, Grup d´Esplai (2004)','Algimia d´Alfara','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Vallada Grup d´Esplai Esportiu Valladins (2008)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Siete Aguas Club de Pilota Valenciana (2010)','','{"president":"Juan Manuel Lopezosa Vela","secretari":"Luis Miralles Bellver"}');
insert into club(nom,poblacio,json)values('Llosa de Ranes Club de Pilota Valenciana El Dauet (2010)','','{"president":"José Julio Cabanes Sanchis","secretari":"José Federico Marín Vila"}');
insert into club(nom,poblacio,json)values('Nàquera Club de Pilota Valenciana (2010)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Tavernes Blanques Club de Pilota Valenciana Carraixet (2010)','','{"president":"Elvira López Cabrero","secretari":"Paula Cuenca Valero"}');
insert into club(nom,poblacio,json)values('Potries Club de Pilota Valenciana Triesport Potries (2010)','','{"president":"--","secretari":"--"}');
insert into club(nom,poblacio,json)values('Enova (l´) Club de Pilota Valenciana (2002)','','{"president":"Daniel Martínez Peiró","secretari":"Rafael Marco Cebrià"}');
insert into club(nom,poblacio,json)values('València Club de Pilota Valenciana Campanar (1988)','','{"president":"Rafael Guillot Garcia","secretari":"Enrique Salon Garcia"}');
insert into club(nom,poblacio,json)values('Castell de Castells Club de Pilota Valenciana Val i Ratlla (2011) ','','{"president":"Eliseo Mezquida Vaquer","secretari":"Carlos Ortola Perez"}');
insert into club(nom,poblacio,json)values('Planes, Club de Pilota Valenciana de Planes (2014)','Planes','{"president":"José Torregrosa Pascual","secretari":"Eugenio Cloquell Cloquell"}');
insert into club(nom,poblacio,json)values('Picassent, Club de Pilota Valenciana Picassent (2011)','Picassent','{"president":"Miguel Ángel Gómez Campos","secretari":"Aurelio Martorell Campos"}');
insert into club(nom,poblacio,json)values('Algímia d´Alfara, Club Pilota Valenciana (2011)','Algímia d´Alfara','{"president":"Enrique Navarro Company","secretari":"Edelmiro Codina Canet"}');
insert into club(nom,poblacio,json)values('Santa Pola Club Esportiu de Pilota Valenciana','','{"president":"Hugo Pons Sarrión","secretari":"Mª José Sarrión Llull"}');
insert into club(nom,poblacio,json)values('València, Club de Pilota ´Els Inmortals´ (2011)','València','{"president":"Bernardo Celda","secretari":"José Vicente Calvo Escutia"}');
insert into club(nom,poblacio,json)values('Estivella, Club Pilota Valenciana Estivella (2011)','Estivella','{"president":"Jordi Barcelona Senent","secretari":"Raúl Moreno Calvo"}');
insert into club(nom,poblacio,json)values('Sumacàrcer, Club de Pilota Valenciana de Sumacárcer (2011)','Sumacàrcer','{"president":"Vicente Ramón Sánchez Flores de Quiñones","secretari":"Francisco Sanchis Pascual"}');
insert into club(nom,poblacio,json)values('Les Valls, Club de Pilota Valenciana Les Valls (2013)','Les Valls','{"president":"Martín Aldabas Lairón","secretari":"Joaquín Gollart Santa Bárbara"}');
insert into club(nom,poblacio,json)values('Moixent, Club de Pilota Valenciana Guerrer de Moixent (2013)','Moixent','{"president":"Jaime Micó Casanova","secretari":"Emilia Isabel Navarro Belda"}');
insert into club(nom,poblacio,json)values('Llíber, Club de Pilota Valenciana Llíber (2013)','Llíber','{"president":"Aitor Ferrer Reus","secretari":"Santiago Ferrer Reus"}');
insert into club(nom,poblacio,json)values('Barxeta, Club de Pilota Valenciana (2012)','Barxeta','{"president":"Borja Ordiñana Sanchis","secretari":"Alfonso Moltó Puertas"}');
insert into club(nom,poblacio,json)values('Gavarda, Club de Pilota Valenciana Gavarda (2012)','Gavarda','{"president":"Vicente Hernández Guillem","secretari":"Carlos Martínez Pavía"}');
insert into club(nom,poblacio,json)values('Bocairent, Club Pilota Valenciana Bocairent (2013)','Bocairent','{"president":"Javier Cantó Vañó","secretari":"Juan Calabuig Ferré"}');
insert into club(nom,poblacio,json)values('Pego, Club Pilota Valenciana Pego (2013)','Pego','{"president":"Abel Alemany Pons","secretari":"Daniel Palacios Costa"}');
insert into club(nom,poblacio,json)values('Gandia, Club de Pilota Valenciana Trinquet Ducal (2014)','Gandia','{"president":"Emilio Peris Mascarell","secretari":"Verónica Aparisi Chorro"}');
insert into club(nom,poblacio,json)values('Guadassuar, Club de Pilota Valenciana Guadassuar (2014)','Guadassuar','{"president":"Juan Talavera Puig","secretari":"Bernat Nerbón Vendrell"}');
insert into club(nom,poblacio,json)values('Rafelbunyol, Club de Pilota ValencianaEl Dau de Rafelbunyol (2014)','Rafelbunyol','{"president":"Antonio Doménech Zorrilla","secretari":"Màxim Piquer Gaspar"}');
insert into club(nom,poblacio,json)values('Calp, Club de Pilota Valenciana de Calp (2014)','Calp','{"president":"Laureano Enrique Llinares Sala","secretari":"Agustín Pineda Fluixà"}');
insert into club(nom,poblacio,json)values('Carlet, Club de Pilota Valenciana ´Amics del trinquet de Carlet´ (2014)','Carlet','{"president":"Blai Signes Fort","secretari":"Álvaro Morales Patón"}');
insert into club(nom,poblacio,json)values('Planes, Club de Pilota Valenciana de Planes (2014)','Planes','{"president":"José Torregrosa Pascual","secretari":"Eugenio Cloquell Cloquell"}');
insert into club(nom,poblacio,json)values('Tormos, Club de Pilota Valenciana de Tormos (2014)','Tormos','{"president":"Juan Fabián Arbona Pons","secretari":"Vicente David Molines Vives"}');
insert into club(nom,poblacio,json)values('Favara, Club Pilota Valenciana Favara (2014)','Favara','{"president":"Lucia García Meliá","secretari":"Vanesa Cebolla García"}');
insert into club(nom,poblacio,json)values('Museros, Club Pilota Valenciana Museros (2015)','Museros','{"president":"Enrique Ruiz Gimeno","secretari":"Domingo Miguel Palacios Nevado"}');
insert into club(nom,poblacio,json)values('Valencia, Club de Pilota Valenciana Més Pilota (2014)','Valencia','{"president":"Jose Agusti Martí Navarro","secretari":"Oscar Sánchez Torrubia"}');
insert into club(nom,poblacio,json)values('Gandia, Club Esportiu a Mà Pilota el Palquet (2014)','Gandia','{"president":"Waldo Vila Gilabert","secretari":"Laura Cabrera López-Fuentes"}');
insert into club(nom,poblacio,json)values('Bellreguard, Club Pilota Valenciana Bellreguard (2015)','Bellreguard','{"president":"Juan Vicente Climent Richart","secretari":"Joan Baptista Pellicer Rocher"}');
insert into club(nom,poblacio,json)values('Altea, Club Pilota Valenciana Altea (2015)','Altea','{"president":"Diego Mulet Orozco","secretari":"Margarita Ripoll Ferrando"}');
insert into club(nom,poblacio,json)values('El Verger, Club de Pilota Valenciana Segària El Verger (2015)','El Verger','{"president":"Miguel Ángel Arbona Muñoz","secretari":"José Salvador Sapena Cervera"}');
insert into club(nom,poblacio,json)values('L´Alcudia, Club de Pilota Valenciana de l´Alcudia (2015)','L´Alcudia','{"president":"Manuel Pastor Moratalla","secretari":"Felipe Escudero Nuñez"}');
insert into club(nom,poblacio,json)values('Alcàncera-Càrcer, Club de Pilota Valencina la Vall Farta de Alcàntera-Càrcer (2016)','Alcàncera-Càrcer','{"president":"Ricardo Sales Roig","secretari":"David Sanjuan Lamata"}');
insert into club(nom,poblacio,json)values('Picanya, Club de Pilota Valenciana de Picanya (2015)','Picanya','{"president":"Roberto García Hernández","secretari":"Jordi Gil Martínez"}');
insert into club(nom,poblacio,json)values('Beniarbeig, Club Pilota Valenciana Beniarbeig','Beniarbeig','{"president":"Vicent Andreu Riera Palonés","secretari":"Beatriz Gavila Gil"}');
insert into club(nom,poblacio,json)values('València, Club Pilota Valenciana Socarrades Campanar','València','{"president":"Josep Maria Escrivà i Anrubia","secretari":"Alfred Contreras i Murillo"}');
insert into club(nom,poblacio,json)values('Ribera Alta, Club Pilota Valenciana Amics de la Ribera (2016)','Ribera Alta','{"president":"Juan Talavera Puig","secretari":"Enrique Cebolla Baldoví"}');